resilience4j:
  circuitbreaker:
    instances:
      ad:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50 # 에러 비율로 해당 값 이상으로 에러 발생시 서킷이 open
        slowCallRateThreshold: 100
        minimumNumberOfCalls: 3 # circuitbreaker가 에러비율 또는 slow call 비율을 계산하기 전에 요구되는 최소 호출 횟수

logging.level:
  org.hibernate.SQL: debug